version: '3'

services:
  app:
    build:
      context: .
    ports:
    - 5000:5000
    environment:
      PG_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 5000:5432